version: '3.8'


services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27018:27017
    env_file:
      - .env
    volumes:
      - db_dev:/var/lib/mongo/data


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env
    volumes:
      - db:/var/lib/mongo-express/data
    depends_on:
      - mongo

volumes:
  db_dev:
  db:
